name: "Linter"

on: [ pull_request ]
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
      
      - name: Install dependencies
        run: composer install --profile --ignore-platform-reqs 

      - name: Run Linter
        run: composer lint